<?php

namespace Enfi\CienciasDoAmbiente\CommonEntitiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PontoDeColetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PontoDeColetaRepository extends EntityRepository
{
}
